# Generated by Django 2.2.3 on 2019-08-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfData',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('data', models.TextField()),
            ],
        ),
    ]
